last: 5
images:
  k8s.gcr.io:
    - etcd
    - coredns
    - kube-proxy
    - kube-apiserver
    - kube-scheduler
    - kube-controller-manager
    - metrics-server/metrics-server
    - ingress-nginx/controller
    - dns/k8s-dns-node-cache