last: 5
images:
  k8s.gcr.io:
    - etcd
    - kube-proxy
    - kube-apiserver
    - kube-scheduler
    - kube-controller-manager
    - coredns/coredns
    - dns/k8s-dns-node-cache
    - metrics-server/metrics-server
    - ingress-nginx/controller
    - ingress-nginx/kube-webhook-certgen
    - sig-storage/nfs-subdir-external-provisioner
    - kube-state-metrics/kube-state-metrics
